title: By Kendra
description: >-
  A quiet corner of the internet for honest reflections, gentle guidance, and
  resources to help navigate life, work, and faith with clarity and peace.
social_media_share_image: /uploads/kmc-logo-2.png
disqus-identifier:
google-analytics: Professional resume writing service
